
default: pdf

TARGET_BASE = morrill.cmput681.project.report.dec2_2013
DVI_COMMAND := cd build && latex $(TARGET_BASE)

build:
	cp -r src build

dvi: clean src/$(TARGET_BASE).tex build
	$(DVI_COMMAND)
	cd build && bibtex $(TARGET_BASE)
	$(DVI_COMMAND)
	$(DVI_COMMAND) # Odd latex thing necessary for references
	mv build/$(TARGET_BASE).dvi ./
	
pdf: dvi
	dvipdf $(TARGET_BASE).dvi

clean:
	-rm -rf build
	-rm *.pdf *.dvi
